import type { Experiment } from './types';

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export function seedExperiments(): Experiment[] {
  return [
    {
      id: 'e1',
      title: 'Cold showers experiment',
      hypothesis: 'A 5-minute cold shower each morning improves my focus by mid-morning.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 21,
      durationUnit: 'days',
      column: 'backlog',
      checkins: [],
      retro: null,
      shared: false,
      shareToken: null,
      createdAt: daysAgo(1),
    },
    {
      id: 'e2',
      title: 'No phone before 9am',
      hypothesis: 'Delaying phone use for the first hour reduces morning anxiety.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 14,
      durationUnit: 'days',
      column: 'backlog',
      checkins: [],
      retro: null,
      shared: false,
      shareToken: null,
      createdAt: daysAgo(1),
    },
    {
      id: 'e3',
      title: '10-minute journaling',
      hypothesis: 'Journaling before bed improves how rested I feel the next day.',
      cadence: 'Daily',
      checkinType: 'rating',
      durationValue: 4,
      durationUnit: 'weeks',
      column: 'active',
      checkins: [
        { id: 'c1', value: '4', note: 'Felt clear-headed after.', createdAt: daysAgo(2) },
        { id: 'c2', value: '3', note: '', createdAt: daysAgo(1) },
        { id: 'c3', value: '5', note: 'Best sleep this week.', createdAt: daysAgo(0) },
      ],
      retro: null,
      shared: true,
      shareToken: 'e3x9k2',
      createdAt: daysAgo(12),
    },
    {
      id: 'e4',
      title: 'Walk after lunch',
      hypothesis: 'A short walk after lunch reduces my 3pm energy crash.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 3,
      durationUnit: 'weeks',
      column: 'active',
      checkins: [
        { id: 'c4', value: 'done', note: '', createdAt: daysAgo(3) },
        { id: 'c5', value: 'done', note: 'Took the long way, felt great.', createdAt: daysAgo(2) },
      ],
      retro: null,
      shared: false,
      shareToken: null,
      createdAt: daysAgo(9),
    },
    {
      id: 'e5',
      title: 'Weekly meal prep',
      hypothesis: 'Prepping meals on Sunday cuts weekday decision fatigue.',
      cadence: 'Weekly',
      checkinType: 'done',
      durationValue: 6,
      durationUnit: 'weeks',
      column: 'active',
      checkins: [{ id: 'c6', value: 'done', note: '', createdAt: daysAgo(8) }],
      retro: null,
      shared: false,
      shareToken: null,
      createdAt: daysAgo(20),
    },
    {
      id: 'e6',
      title: 'Read 20 pages before bed',
      hypothesis: 'Reading instead of scrolling helps me fall asleep faster.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 2,
      durationUnit: 'weeks',
      column: 'reflect',
      checkins: [
        { id: 'c7', value: 'done', note: '', createdAt: daysAgo(6) },
        { id: 'c8', value: 'skip', note: 'Too tired.', createdAt: daysAgo(4) },
        { id: 'c9', value: 'done', note: '', createdAt: daysAgo(2) },
      ],
      retro: null,
      shared: false,
      shareToken: null,
      createdAt: daysAgo(14),
    },
    {
      id: 'e7',
      title: 'Standing desk for a week',
      hypothesis: 'Standing more during work reduces afternoon back pain.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 1,
      durationUnit: 'weeks',
      column: 'archived',
      checkins: [{ id: 'c10', value: 'done', note: '', createdAt: daysAgo(9) }],
      retro: {
        worked: 'Noticed less stiffness by day 3.',
        notWorked: 'Forgot to switch back down before calls.',
        decision: 'continue',
      },
      shared: false,
      shareToken: null,
      createdAt: daysAgo(16),
    },
    {
      id: 'e8',
      title: 'Track water intake',
      hypothesis: 'Logging water intake would help me drink more during the day.',
      cadence: 'Daily',
      checkinType: 'done',
      durationValue: 10,
      durationUnit: 'days',
      column: 'archived',
      checkins: [],
      retro: {
        worked: 'Nothing really.',
        notWorked: 'Logging felt like a chore, gave up by day 4.',
        decision: 'stop',
      },
      shared: false,
      shareToken: null,
      createdAt: daysAgo(18),
    },
  ];
}
